### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(UntitledProject1)
add_subdirectory(UntitledProject1Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_A1plugin
    Generated_QtQuick3D_A2plugin
    Generated_QtQuick3D_A3plugin
    Generated_QtQuick3D_A3_1plugin
    Generated_QtQuick3D_A4plugin
    Generated_QtQuick3D_A5plugin
    Generated_QtQuick3D_A6plugin
    Generated_QtQuick3D_Baseplugin
    UntitledProject1plugin
    UntitledProject1Contentplugin
    QtQuickDesignerComponents)